<?php
$allowedtags = array(
'a' => array(
	'class' => array (),
	'href' => array (),
	'id' => array (),
	'title' => array (),
	'rel' => array (),
	'rev' => array (),
	'name' => array (),
	'target' => array()),
'abbr' => array(
	'class' => array (),
	'title' => array ()),
'acronym' => array(
	'title' => array ()),
'b' => array(),
'big' => array(),
'blockquote' => array(
	'id' => array (),
	'cite' => array (),
	'class' => array(),
	'lang' => array(),
	'xml:lang' => array()),
'br' => array (
	'class' => array ()),
'cite' => array (
	'class' => array(),
	'dir' => array(),
	'lang' => array(),
	'title' => array ()),
'code' => array (
	'style' => array()),
'del' => array(
	'datetime' => array ()),
'dd' => array(),
'div' => array(
	'align' => array (),
	'class' => array (),
	'dir' => array (),
	'lang' => array(),
	'style' => array (),
	'xml:lang' => array()),
'dl' => array(),
'dt' => array(),
'em' => array(),
'font' => array(
	'color' => array (),
	'face' => array (),
	'size' => array ()),
'hr' => array (
	'align' => array (),
	'class' => array (),
	'noshade' => array (),
	'size' => array (),
	'width' => array ()),
'i' => array(),
'img' => array(
	'alt' => array (),
	'align' => array (),
	'border' => array (),
	'class' => array (),
	'height' => array (),
	'hspace' => array (),
	'longdesc' => array (),
	'vspace' => array (),
	'src' => array (),
	'style' => array (),
	'width' => array ()),
'li' => array (
	'align' => array (),
	'class' => array ()),
'p' => array(
	'class' => array (),
	'align' => array (),
	'dir' => array(),
	'lang' => array(),
	'style' => array (),
	'xml:lang' => array()),
'pre' => array(
	'style' => array(),
	'width' => array ()),
'q' => array(
	'cite' => array ()),
'span' => array (
	'class' => array (),
	'dir' => array (),
	'align' => array (),
	'lang' => array (),
	'style' => array (),
	'title' => array (),
	'xml:lang' => array()),
'strike' => array(),
'strong' => array(),
'sub' => array(),
'sup' => array(),
'u' => array(),
'ul' => array (
	'class' => array (),
	'style' => array (),
	'type' => array ()),
'ol' => array (
	'class' => array (),
	'start' => array (),
	'style' => array (),
	'type' => array ()),
'var' => array ()
);